In [2]:
import pandas as pd
import numpy as np

data=np.random.rand(2,3,4)
zeros=np.zeros((2,2,2))
ones=np.ones((2,2,2))
full=np.full((2,2,2),7)

'''
print(zeros)
print(ones)
print(full)
'''
print(data)

[[[8.28159526e-01 2.48671211e-01 8.42180044e-04 3.62760967e-01]
  [2.25628258e-01 9.21643575e-02 1.83514224e-01 1.95353399e-02]
  [3.14182161e-01 3.11256477e-01 6.96200823e-01 3.89897868e-01]]

 [[7.24928643e-01 1.68573109e-01 1.47025109e-01 6.05501659e-01]
  [2.22787063e-01 8.72015262e-01 2.60539634e-01 8.59581714e-01]
  [3.88248202e-01 5.08801398e-01 7.20252835e-01 4.74638754e-01]]]


In [3]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
type(arr)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
# Attributes
shape=data.shape
size=data.size
dtype=data.dtype

print(shape)
print(size)
print(dtype)

(2, 3, 4)
24
float64


In [5]:
# 1D Array Slicing

arr1d=np.array([10,20,30,40,50])

print(arr1d[1:4])
print(arr1d[:3])
print(arr1d[2:])
print(arr1d[::2])
print(arr1d[::-1])

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]
[50 40 30 20 10]


In [6]:
# 2D Array Slicing

arr2d=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print(arr2d[0:]) # Prints all rows
print(arr2d[:1]) # Prints first row
print(arr2d[1:3,0:2]) # Extracts sub-matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[[4 5]
 [7 8]]


In [7]:
# Boolean Slicing (Filtering)

arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])

[30 40 50]


In [8]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 15, 25, 35, 45])

# Basic Math
add=np.add(arr1,arr2)
sub=np.subtract(arr1,arr2)
div=np.divide(arr1,arr2)
mul=np.multiply(arr1,arr2)
dot=np.dot(arr1,arr2)

print(add)

[15 35 55 75 95]


In [9]:
# Stat Functions
sqrt=np.sqrt(25)
ab=np.abs(-2)
power=np.power(2,7)
log=np.log(25)
exp=np.exp([2,3])
mins=np.min(arr1)
maxs=np.max(arr1)

print(sqrt)

5.0


In [10]:
# Shape
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([[1, 2, 3],  
                 [4, 5, 6]])

print(arr1.shape)  # (5,) → 1D array with 5 elements
print(arr2.shape)  # (2, 3) → 2D array with 2 rows & 3 columns

(5,)
(2, 3)


In [11]:
# Reshape
arr1 = np.array([10, 20, 30, 40, 50, 60])
reshaped_arr=arr1.reshape(2,3)
print(reshaped_arr)

[[10 20 30]
 [40 50 60]]


In [12]:
# Reshape with -1 (Auto Calculation)
arr1 = np.array([10, 20, 30, 40, 50, 60])
reshaped_arr=arr1.reshape(3,-1) # 3 rows, NumPy calculates columns
print(reshaped_arr)

[[10 20]
 [30 40]
 [50 60]]


In [13]:
# Sort
arr1 = np.array([30, 10, 50, 20, 40])
sorted_arr=np.sort(arr1)
print(sorted_arr)
'''It can sort 2d array to but in there respective rows'''

[10 20 30 40 50]


'It can sort 2d array to but in there respective rows'

In [14]:
# Inserting into a 1D Array
arr1 = np.array([10, 20, 40, 50, 60])
new_arr1=np.insert(arr1,2,30) # Insert 30 at index 2
print(new_arr1)

[10 20 30 40 50 60]


In [15]:
# Inserting into a 2D Array
arr2 = np.array([[1, 2, 3],  
                  [4, 5, 6]])
new_arr2=np.insert(arr2,2,[7, 8, 9],axis=0)
print(new_arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# Flatten (Convert to 1D)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr2d.flatten()
print(flat_arr) 

[1 2 3 4 5 6]


In [17]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2d = np.array([[1, 2, 3],  
                  [4, 5, 6],  
                  [7, 8, 9]])

# Deleting index 2 from arr1
arr1_new = np.delete(arr1, 2)  
print(arr1_new)  

# Deleting indices 1 and 3 from arr1
arr1_new2 = np.delete(arr1, [1, 3])  
print(arr1_new2)  

# Deleting row at index 1 from arr2d (axis=0 means row-wise deletion)
arr2d_new = np.delete(arr2d, 1, axis=0)  
print(arr2d_new)

# Deleting column at index 2 from arr2d (axis=1 means column-wise deletion)
arr2d_new2 = np.delete(arr2d, 2, axis=1)  
print(arr2d_new2)

[10 20 40 50]
[10 30 50]
[[1 2 3]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
